Fix #1: Exception on empty result set from query
An exception is raised when one of the queries returns an empty result
set:

<sqlalchemy.engine.result.ResultProxy object at 0x03AAA190>
Traceback (most recent call last):
File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\python\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Python\Scripts\sqlexceller.exe_main.py", line 9, in
File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 246, in main
process_queries(cfg)
File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 241, in process_queries
output.write_query(query)
File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 195, in write_query
if row_data and self._column_titles:
UnboundLocalError: local variable 'row_data' referenced before assignment

The code was assuming that we would always have rows, with this patch we
no longer do that.